/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Driver {
  'id' : DriverId,
  'name' : string,
  'isOnline' : boolean,
  'isActive' : boolean,
  'carNumber' : string,
  'phone' : string,
}
export type DriverId = bigint;
export interface Ride {
  'id' : RideId,
  'status' : RideStatus,
  'driverIdOpt' : [] | [DriverId],
  'createdAt' : bigint,
  'dropLocation' : string,
  'estimatedFare' : bigint,
  'riderPhone' : string,
  'riderName' : string,
  'pickupLocation' : string,
}
export type RideId = bigint;
export type RideStatus = { 'Accepted' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface UserProfile { 'driverId' : [] | [DriverId], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptRide' : ActorMethod<[RideId, DriverId], undefined>,
  'addDriver' : ActorMethod<[string, string, string], DriverId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDriver' : ActorMethod<[DriverId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDrivers' : ActorMethod<[], Array<Driver>>,
  'getOnlineDrivers' : ActorMethod<[], Array<Driver>>,
  'getRides' : ActorMethod<[], Array<Ride>>,
  'getRidesByStatus' : ActorMethod<[RideStatus], Array<Ride>>,
  'getRidesForDriver' : ActorMethod<[DriverId], Array<Ride>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestRide' : ActorMethod<[string, string, string, string, bigint], RideId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleDrivers' : ActorMethod<[], undefined>,
  'toggleDriverOnline' : ActorMethod<[DriverId], undefined>,
  'updateDriver' : ActorMethod<[DriverId, string, string, string], undefined>,
  'updateRideStatus' : ActorMethod<[RideId, RideStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];