/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RideId = IDL.Nat;
export const DriverId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'driverId' : IDL.Opt(DriverId),
  'name' : IDL.Text,
});
export const Driver = IDL.Record({
  'id' : DriverId,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'isActive' : IDL.Bool,
  'carNumber' : IDL.Text,
  'phone' : IDL.Text,
});
export const RideStatus = IDL.Variant({
  'Accepted' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Ride = IDL.Record({
  'id' : RideId,
  'status' : RideStatus,
  'driverIdOpt' : IDL.Opt(DriverId),
  'createdAt' : IDL.Int,
  'dropLocation' : IDL.Text,
  'estimatedFare' : IDL.Nat,
  'riderPhone' : IDL.Text,
  'riderName' : IDL.Text,
  'pickupLocation' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRide' : IDL.Func([RideId, DriverId], [], []),
  'addDriver' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [DriverId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDriver' : IDL.Func([DriverId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'getOnlineDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'getRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
  'getRidesByStatus' : IDL.Func([RideStatus], [IDL.Vec(Ride)], ['query']),
  'getRidesForDriver' : IDL.Func([DriverId], [IDL.Vec(Ride)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestRide' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [RideId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleDrivers' : IDL.Func([], [], []),
  'toggleDriverOnline' : IDL.Func([DriverId], [], []),
  'updateDriver' : IDL.Func([DriverId, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateRideStatus' : IDL.Func([RideId, RideStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RideId = IDL.Nat;
  const DriverId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'driverId' : IDL.Opt(DriverId),
    'name' : IDL.Text,
  });
  const Driver = IDL.Record({
    'id' : DriverId,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'isActive' : IDL.Bool,
    'carNumber' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RideStatus = IDL.Variant({
    'Accepted' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Ride = IDL.Record({
    'id' : RideId,
    'status' : RideStatus,
    'driverIdOpt' : IDL.Opt(DriverId),
    'createdAt' : IDL.Int,
    'dropLocation' : IDL.Text,
    'estimatedFare' : IDL.Nat,
    'riderPhone' : IDL.Text,
    'riderName' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRide' : IDL.Func([RideId, DriverId], [], []),
    'addDriver' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [DriverId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDriver' : IDL.Func([DriverId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'getOnlineDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'getRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
    'getRidesByStatus' : IDL.Func([RideStatus], [IDL.Vec(Ride)], ['query']),
    'getRidesForDriver' : IDL.Func([DriverId], [IDL.Vec(Ride)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestRide' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [RideId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleDrivers' : IDL.Func([], [], []),
    'toggleDriverOnline' : IDL.Func([DriverId], [], []),
    'updateDriver' : IDL.Func([DriverId, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateRideStatus' : IDL.Func([RideId, RideStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };